# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2237057668a60c79586f50faef345b43d8ec2482b0608c9054b3ccb78f816e6e86643499a10623f7ae6cf56dc6e545b2abb5fbc683faeafef7c0648c465ecca

test:
  secret_key_base: 20ae8a61889e93a354b1d63ba06641a25ba81a9fea47ed35a7946968fc9095d7feabc4ea8d3aed07395187185d438bdb3eb57e0e30e6d9837ddaa45b358634bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
